name: Deploy Node App to Azure WebApp

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Oryx
        run: |
          curl -L https://github.com/microsoft/Oryx/releases/latest/download/oryx-cli-linux-x64.tar.gz -o oryx.tar.gz
          mkdir oryx
          tar -xzf oryx.tar.gz -C oryx
          sudo mv oryx/oryx /usr/local/bin/oryx
          oryx --version

      - name: Install dependencies
        run: |
          cd app
          npm install --production

      - name: Build app using Oryx
        run: |
          oryx build app -o output

      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "app-azurewebapp123-dev"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: output
